apiVersion: apps/v1
kind: Deployment
metadata:
  name: team3-backend
  labels:
    app: team3-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: team3-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: team3-backend
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: team3-backend
          image: 672381912436.dkr.ecr.ap-northeast-2.amazonaws.com/team3-ecr-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://team3-rds-mysql.cxljtidrhi5i.ap-northeast-2.rds.amazonaws.com:3306/demo_table?useSSL=true&requireSSL=true&serverTimezone=Asia/Seoul"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
          resources:
            requests:
              cpu: "250m"
              memory: "384Mi"
            limits:
              cpu: "500m"
              memory: "768Mi"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: team3-backend-svc
spec:
  type: ClusterIP
  selector:
    app: team3-backend
  ports:
    - port: 80
      targetPort: 8080
